"use strict";
var __cov_Em$VfGLRY6cGqR5zODenJw = (Function('return this'))();
if (!__cov_Em$VfGLRY6cGqR5zODenJw.$$coverage$$) { __cov_Em$VfGLRY6cGqR5zODenJw.$$coverage$$ = {}; }
__cov_Em$VfGLRY6cGqR5zODenJw = __cov_Em$VfGLRY6cGqR5zODenJw.$$coverage$$;
if (!(__cov_Em$VfGLRY6cGqR5zODenJw['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\view2\\view2_test.js'])) {
   __cov_Em$VfGLRY6cGqR5zODenJw['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\view2\\view2_test.js'] = {"path":"c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\view2\\view2_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":3,"loc":{"start":{"line":3,"column":31},"end":{"line":3,"column":42}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":31},"end":{"line":7,"column":41}}},"3":{"name":"(anonymous_3)","line":9,"loc":{"start":{"line":9,"column":29},"end":{"line":9,"column":51}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":16,"column":3}},"2":{"start":{"line":5,"column":2},"end":{"line":5,"column":36}},"3":{"start":{"line":7,"column":2},"end":{"line":15,"column":5}},"4":{"start":{"line":9,"column":4},"end":{"line":13,"column":8}},"5":{"start":{"line":11,"column":6},"end":{"line":11,"column":47}},"6":{"start":{"line":12,"column":6},"end":{"line":12,"column":38}}},"branchMap":{}};
}
__cov_Em$VfGLRY6cGqR5zODenJw = __cov_Em$VfGLRY6cGqR5zODenJw['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\view2\\view2_test.js'];
__cov_Em$VfGLRY6cGqR5zODenJw.s['1']++;describe('myApp.view2 module',function(){__cov_Em$VfGLRY6cGqR5zODenJw.f['1']++;__cov_Em$VfGLRY6cGqR5zODenJw.s['2']++;beforeEach(module('myApp.view2'));__cov_Em$VfGLRY6cGqR5zODenJw.s['3']++;describe('view2 controller',function(){__cov_Em$VfGLRY6cGqR5zODenJw.f['2']++;__cov_Em$VfGLRY6cGqR5zODenJw.s['4']++;it('should ....',inject(function($controller){__cov_Em$VfGLRY6cGqR5zODenJw.f['3']++;__cov_Em$VfGLRY6cGqR5zODenJw.s['5']++;var view2Ctrl=$controller('View2Ctrl');__cov_Em$VfGLRY6cGqR5zODenJw.s['6']++;expect(view2Ctrl).toBeDefined();}));});});
