"use strict";
var __cov_$ona188z_DXSO0pwAcA6SA = (Function('return this'))();
if (!__cov_$ona188z_DXSO0pwAcA6SA.$$coverage$$) { __cov_$ona188z_DXSO0pwAcA6SA.$$coverage$$ = {}; }
__cov_$ona188z_DXSO0pwAcA6SA = __cov_$ona188z_DXSO0pwAcA6SA.$$coverage$$;
if (!(__cov_$ona188z_DXSO0pwAcA6SA['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\components\\version\\version_test.js'])) {
   __cov_$ona188z_DXSO0pwAcA6SA['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\components\\version\\version_test.js'] = {"path":"c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\components\\version\\version_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":3,"loc":{"start":{"line":3,"column":33},"end":{"line":3,"column":44}}},"2":{"name":"(anonymous_2)","line":6,"loc":{"start":{"line":6,"column":30},"end":{"line":6,"column":41}}},"3":{"name":"(anonymous_3)","line":7,"loc":{"start":{"line":7,"column":47},"end":{"line":7,"column":65}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":11,"column":3}},"2":{"start":{"line":4,"column":2},"end":{"line":4,"column":38}},"3":{"start":{"line":6,"column":2},"end":{"line":10,"column":5}},"4":{"start":{"line":7,"column":4},"end":{"line":9,"column":8}},"5":{"start":{"line":8,"column":6},"end":{"line":8,"column":37}}},"branchMap":{}};
}
__cov_$ona188z_DXSO0pwAcA6SA = __cov_$ona188z_DXSO0pwAcA6SA['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\angular-seed\\angular-seed\\app\\components\\version\\version_test.js'];
__cov_$ona188z_DXSO0pwAcA6SA.s['1']++;describe('myApp.version module',function(){__cov_$ona188z_DXSO0pwAcA6SA.f['1']++;__cov_$ona188z_DXSO0pwAcA6SA.s['2']++;beforeEach(module('myApp.version'));__cov_$ona188z_DXSO0pwAcA6SA.s['3']++;describe('version service',function(){__cov_$ona188z_DXSO0pwAcA6SA.f['2']++;__cov_$ona188z_DXSO0pwAcA6SA.s['4']++;it('should return current version',inject(function(version){__cov_$ona188z_DXSO0pwAcA6SA.f['3']++;__cov_$ona188z_DXSO0pwAcA6SA.s['5']++;expect(version).toEqual('0.1');}));});});
