"use strict";
var __cov_RDovhBib7NFhNMFcfFZnEQ = (Function('return this'))();
if (!__cov_RDovhBib7NFhNMFcfFZnEQ.$$coverage$$) { __cov_RDovhBib7NFhNMFcfFZnEQ.$$coverage$$ = {}; }
__cov_RDovhBib7NFhNMFcfFZnEQ = __cov_RDovhBib7NFhNMFcfFZnEQ.$$coverage$$;
if (!(__cov_RDovhBib7NFhNMFcfFZnEQ['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\FIXED_ISTANBUL\\app\\view1\\view1.js'])) {
   __cov_RDovhBib7NFhNMFcfFZnEQ['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\FIXED_ISTANBUL\\app\\view1\\view1.js'] = {"path":"c:\\Users\\mbiel\\Desktop\\WORKSPACE\\FIXED_ISTANBUL\\app\\view1\\view1.js","s":{"1":0,"2":0,"3":1,"4":0,"5":1,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"(anonymous_1)","line":2,"loc":{"start":{"line":2,"column":1},"end":{"line":2,"column":13}}},"2":{"name":"routesConfig","line":7,"loc":{"start":{"line":7,"column":1},"end":{"line":7,"column":40}}},"3":{"name":"View1Ctrl","line":14,"loc":{"start":{"line":14,"column":1},"end":{"line":14,"column":29}}},"4":{"name":"(anonymous_4)","line":15,"loc":{"start":{"line":15,"column":26},"end":{"line":15,"column":38}}}},"statementMap":{"1":{"start":{"line":2,"column":0},"end":{"line":20,"column":5}},"2":{"start":{"line":3,"column":1},"end":{"line":5,"column":50}},"3":{"start":{"line":7,"column":1},"end":{"line":12,"column":2}},"4":{"start":{"line":8,"column":3},"end":{"line":11,"column":6}},"5":{"start":{"line":14,"column":1},"end":{"line":19,"column":2}},"6":{"start":{"line":15,"column":2},"end":{"line":18,"column":4}},"7":{"start":{"line":16,"column":3},"end":{"line":16,"column":24}},"8":{"start":{"line":17,"column":3},"end":{"line":17,"column":24}}},"branchMap":{}};
}
__cov_RDovhBib7NFhNMFcfFZnEQ = __cov_RDovhBib7NFhNMFcfFZnEQ['c:\\Users\\mbiel\\Desktop\\WORKSPACE\\FIXED_ISTANBUL\\app\\view1\\view1.js'];
__cov_RDovhBib7NFhNMFcfFZnEQ.s['1']++;(function(){__cov_RDovhBib7NFhNMFcfFZnEQ.f['1']++;__cov_RDovhBib7NFhNMFcfFZnEQ.s['2']++;angular.module('myApp.view1',['ngRoute']).config(['$routeProvider',routesConfig]).controller('View1Ctrl',['$scope',View1Ctrl]);function routesConfig($routeProvider){__cov_RDovhBib7NFhNMFcfFZnEQ.f['2']++;__cov_RDovhBib7NFhNMFcfFZnEQ.s['4']++;$routeProvider.when('/view1',{templateUrl:'view1/view1.html',controller:'View1Ctrl'});}function View1Ctrl($scope){__cov_RDovhBib7NFhNMFcfFZnEQ.f['3']++;__cov_RDovhBib7NFhNMFcfFZnEQ.s['6']++;$scope.runSomeActions=function(){__cov_RDovhBib7NFhNMFcfFZnEQ.f['4']++;__cov_RDovhBib7NFhNMFcfFZnEQ.s['7']++;$scope.test='Test';__cov_RDovhBib7NFhNMFcfFZnEQ.s['8']++;console.log('Test!');};}}());
